site: P S H

url: 
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  languages:
    output: true
    permalink: /language/:slug
  it-studies:
    output: true
    permalink: /it-study/:slug    
  projects:
    output: true
    permalink: /project/:slug
  arts:
    output: true
    permalink: /art/:slug
    
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "languages"
    values:
      layout: "language"
  -
    scope:
      path: ""
      type: "it-studies"
    values:
      layout: "it-study"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "arts"
    values:
      layout: "art"      

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  
